name: test

on:
  push:
    branches:
      - main
      - middleware-revamped
  pull_request:
    branches:
      - main

jobs:
  test-node:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: ["16"]
        typescript: ["4.1", "4.2", "4.3", "4.4", "4.5", "4.6"]
    name: Test with TypeScript ${{ matrix.typescript }} on Node ${{ matrix.node }}
    defaults:
      run:
        working-directory: ./package
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - run: pnpm install
      - run: pnpm add typescript@${{ matrix.typescript }}
      - run: pnpm build
      - run: pnpm test
